# Generated by Django 5.2.9 on 2025-12-12 01:19

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_discussion_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video file directly (MP4, MOV, AVI, MKV, WEBM) - Max 500MB",
                null=True,
                upload_to="lesson_videos/",
                validators=[
                    courses.validators.validate_video_file,
                    courses.validators.validate_video_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.IntegerField(default=0, help_text="Duration in minutes"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_free_preview",
            field=models.BooleanField(
                default=False,
                help_text="Allow non-enrolled students to preview this lesson",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[("video", "Video"), ("text", "Text")],
                default="video",
                help_text="Type of lesson content",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.IntegerField(default=0, help_text="Order within the course"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="text_content",
            field=models.TextField(blank=True, help_text="Lesson content in Markdown"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube video URL (if not uploading file)"
            ),
        ),
    ]
